parameters:
    takeit_amp_html.amp_subscriber.class: Takeit\Bundle\AmpHtmlBundle\EventListener\AmpResponseSubscriber
    takeit_amp_html.amp_controller.class: Takeit\Bundle\AmpHtmlBundle\Controller\AmpViewController
    takeit_amp_html.routing_loader.class: Takeit\Bundle\AmpHtmlBundle\Routing\Loader\AmpLoader
    takeit_amp_html.param_converter.resolve_entity_converter.class: Takeit\Bundle\AmpHtmlBundle\Request\ParamConverter\ResolveEntityParamConverter

services:
    takeit_amp_html.amp_subscriber:
        class: %takeit_amp_html.amp_subscriber.class%
        arguments: ["@takeit_amp_html.converter.amp"]
        tags:
            - { name: kernel.event_subscriber, priority: 30 }

    takeit_amp_html.amp_controller:
        class: %takeit_amp_html.amp_controller.class%
        arguments: ["@twig", "%takeit_amp_html.configuration.theme.current_theme%"]

    takeit_amp_html.routing_loader:
        class: %takeit_amp_html.routing_loader.class%
        public: false
        arguments: ["%takeit_amp_html.configuration.routing%"]
        tags:
            - { name: routing.loader }

    takeit_amp_html.param_converter.resolve_entity_converter:
        class: %takeit_amp_html.param_converter.resolve_entity_converter.class%
        public: false
        tags:
            - { name: request.param_converter, priority: 10, converter: doctrine.orm }
        arguments:
            - {'Takeit\Bundle\AmpHtmlBundle\Model\AmpInterface': "%takeit_amp_html.configuration.model.class%"}
            - "@?doctrine"
